import React, { useEffect, useState } from 'react';
import { 
    FileText, 
    Brain, 
    Activity, 
    ChevronRight, 
    Calendar,
    User,
    Download,
    ExternalLink,
    Filter,
    X,
    CheckCircle2,
    AlertCircle,
    Info,
    Clock,
    Zap,
    ChevronDown
} from 'lucide-react';
import { apiGet } from '../../utils/api';
import { useToast } from '../../context/ToastContext';
import { motion, AnimatePresence } from 'framer-motion';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function AdminReports() {
    const { showToast } = useToast();
    const [reports, setReports] = useState(null);
    const [loading, setLoading] = useState(true);
    const [activeTab, setActiveTab] = useState('predictions');
    const [selectedReport, setSelectedReport] = useState(null);

    const getMediaUrl = (path) => {
        if (!path) return '';
        if (path.startsWith('http')) return path;
        const baseUrl = (import.meta.env.VITE_API_URL || 'http://localhost:5000').replace(/\/api\/?$/, '');
        return `${baseUrl}${path}`;
    };

    useEffect(() => {
        fetchReports();
    }, []);

    const fetchReports = async () => {
        try {
            const response = await apiGet('/admin/reports');
            setReports(response.data.reports);
        } catch (err) {
            showToast('Failed to load system reports', 'error');
        } finally {
            setLoading(false);
        }
    };

    const loadImageAsBase64 = (url) => {
        return new Promise((resolve) => {
            const img = new Image();
            img.crossOrigin = "anonymous";
            img.onload = () => {
                const canvas = document.createElement("canvas");
                canvas.width = img.width;
                canvas.height = img.height;
                const ctx = canvas.getContext("2d");
                ctx.drawImage(img, 0, 0);
                resolve(canvas.toDataURL("image/jpeg"));
            };
            img.onerror = () => resolve(null);
            img.src = url;
        });
    };

    const handleExport = async (report) => {
        if (!report) return;
        
        try {
            const { type, data } = report;
            const doc = new jsPDF();
        
        // 1. Header & Title
        doc.setFillColor(30, 41, 59); // Slate-900
        doc.rect(0, 0, 210, 40, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("ALZDETECT SYSTEM REPORT", 20, 25);
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text(`Generated by Administrator on: ${new Date().toLocaleString()}`, 20, 32);

        // 2. Report Summary Section
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Case Summary", 20, 55);
        
        autoTable(doc, {
            startY: 60,
            head: [['Field', 'Detail']],
            body: [
                ['Report Type', type.toUpperCase()],
                ['Case ID', data._id],
                ['Patient Name', data.user?.name || 'Unknown'],
                ['Patient Email', data.user?.email || 'N/A'],
                ['Log Date', new Date(data.createdAt || data.uploadedAt || data.submittedAt).toLocaleString()],
            ],
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229] },
        });

        let currentY = doc.lastAutoTable.finalY + 15;

        // 3. Conditional Content based on Report Type
        if (type === 'prediction') {
            doc.setFontSize(14);
            doc.text("Diagnostic Analysis", 20, currentY);
            
            autoTable(doc, {
                startY: currentY + 5,
                head: [['Metric', 'Value']],
                body: [
                    ['AI Prediction', data.prediction],
                    ['Model Confidence', `${Math.round(data.confidence * 100)}%`],
                    ['Compute Time', data.processingTimeMs ? `${Math.round(data.processingTimeMs)}ms` : 'N/A'],
                    ['Notes', typeof data.details === 'string' ? data.details : 'System-generated assessment'],
                ],
                theme: 'grid',
                headStyles: { fillColor: [79, 70, 229] },
            });

            currentY = doc.lastAutoTable.finalY + 15;

            // MRI Image in Prediction Report
            if (data.mriScan) {
                const imageUrl = getMediaUrl(data.mriScan.fileUrl || data.mriScan.filePath);
                if (imageUrl) {
                    const base64Img = await loadImageAsBase64(imageUrl);
                    if (base64Img) {
                        doc.text("Associated MRI Scan", 20, currentY);
                        doc.addImage(base64Img, 'JPEG', 20, currentY + 5, 100, 70);
                        currentY += 80;
                    }
                }
            }

            // Cognitive scores in Prediction Report
            if (data.cognitiveTest) {
                if (currentY > 240) { doc.addPage(); currentY = 20; }
                doc.text("Clinical Data Scores", 20, currentY);
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['Domain', 'Score']],
                    body: [
                        ['Total Symptom Count', `${data.cognitiveTest.totalScore ?? (30 - data.cognitiveTest.mmseScore) ?? 'N/A'}/30`],
                        ['Memory Performance', `${data.cognitiveTest.memoryScore ?? 'N/A'}%`],
                        ['Attention Performance', `${data.cognitiveTest.attentionScore ?? 'N/A'}%`],
                    ],
                    theme: 'striped',
                    headStyles: { fillColor: [147, 51, 234] },
                });
            }
        } else if (type === 'mri') {
            doc.setFontSize(14);
            doc.text("MRI Scan Analysis", 20, currentY);
            
            const imageUrl = getMediaUrl(data.fileUrl || data.filePath);
            if (imageUrl) {
                const base64Img = await loadImageAsBase64(imageUrl);
                if (base64Img) {
                    doc.addImage(base64Img, 'JPEG', 20, currentY + 5, 120, 85);
                    currentY += 95;
                }
            }

            autoTable(doc, {
                startY: currentY,
                head: [['Property', 'Value']],
                body: [
                    ['File Name', data.fileName],
                    ['File Size', data.fileSize ? (data.fileSize / 1024).toFixed(2) + ' KB' : 'N/A'],
                    ['Linked Prediction', data.result?.prediction || 'None'],
                ],
                theme: 'grid',
            });
        } else if (type === 'cognitive') {
            doc.setFontSize(14);
            doc.text("Cognitive Assessment Metrics", 20, currentY);
            
            autoTable(doc, {
                startY: currentY + 5,
                head: [['Domain', 'Score']],
                body: [
                    ['Total Symptom Count', `${data.totalScore ?? (30 - data.mmseScore) ?? 'N/A'}/30`],
                    ['Memory Performance', `${data.memoryScore ?? 'N/A'}%`],
                    ['Attention Performance', `${data.attentionScore ?? 'N/A'}%`],
                    ['Language Performance', `${data.languageScore ?? 'N/A'}%`],
                    ['Linked Prediction', data.result?.prediction || 'None'],
                ],
                theme: 'striped',
                headStyles: { fillColor: [147, 51, 234] },
            });
        }


            // 4. Footer
            doc.setFontSize(8);
            doc.setTextColor(100);
            doc.text("CONFIDENTIAL MEDICAL RECORD - This report was generated for clinical research purposes.", 20, 285);

            const patientName = (data.user?.name || 'Patient').replace(/\s+/g, '_');
            const fileName = `Clinical_Report_${patientName}_${data._id.slice(-6)}.pdf`;
            doc.save(fileName);
            showToast('Clinical report downloaded successfully', 'success');
        } catch (err) {
            console.error("Admin PDF Export Error:", err);
            showToast(`Failed to export PDF: ${err.message || 'Unknown error'}`, 'error');
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-full">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
            </div>
        );
    }

    const tabs = [
        { id: 'predictions', label: 'Predictions', icon: Activity, count: reports?.predictions?.length || 0 },
        { id: 'mri', label: 'MRI Scans', icon: Brain, count: reports?.mriUploads?.length || 0 },
        { id: 'cognitive', label: 'Cognitive Tests', icon: FileText, count: reports?.cognitiveTests?.length || 0 },
    ];

    return (
        <div className="space-y-8">
            <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900">System Reports</h1>
                    <p className="text-gray-500 mt-1">Unified view of all clinical data across the platform.</p>
                </div>
            </header>

            {/* Tabs */}
            <div className="flex flex-wrap gap-2 p-1 bg-gray-200/50 rounded-2xl w-fit">
                {tabs.map((tab) => (
                    <button
                        key={tab.id}
                        onClick={() => setActiveTab(tab.id)}
                        className={`flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm transition-all ${
                            activeTab === tab.id 
                            ? 'bg-white text-indigo-700 shadow-sm' 
                            : 'text-gray-500 hover:text-gray-700'
                        }`}
                    >
                        <tab.icon size={18} />
                        {tab.label}
                        <span className={`px-2 py-0.5 rounded-full text-[10px] ${
                            activeTab === tab.id ? 'bg-indigo-100' : 'bg-gray-200'
                        }`}>
                            {tab.count}
                        </span>
                    </button>
                ))}
            </div>

            {/* List View */}
            <div className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="divide-y divide-gray-100">
                    {activeTab === 'predictions' && reports?.predictions?.map((pred, i) => (
                        <motion.div 
                            key={pred._id} 
                            initial={{ opacity: 0, y: 10 }} 
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.05 }}
                            className="p-6 hover:bg-gray-50/50 flex flex-col md:flex-row md:items-center justify-between gap-6"
                        >
                            <div className="flex items-center gap-4">
                                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center font-bold text-xl ${
                                    pred.prediction === 'AD' ? 'bg-rose-100 text-rose-600 shadow-rose-200/50' : 
                                    pred.prediction === 'LMCI' ? 'bg-orange-100 text-orange-600 shadow-orange-200/50' : 
                                    pred.prediction === 'EMCI' ? 'bg-amber-100 text-amber-600 shadow-amber-200/50' : 
                                    pred.prediction === 'MCI' ? 'bg-yellow-100 text-yellow-600 shadow-yellow-200/50' : 
                                    'bg-emerald-100 text-emerald-600 shadow-emerald-200/50'
                                } shadow-lg`}>
                                    {pred.prediction[0]}
                                </div>
                                <div>
                                    <h3 className="font-bold text-gray-900 text-lg flex items-center gap-2">
                                        Patient: {pred.user?.name || 'Unknown Patient'}
                                        <span className={`text-xs px-2 py-0.5 rounded-full ${
                                            pred.prediction === 'AD' ? 'bg-rose-100 text-rose-700' : 
                                            pred.prediction === 'LMCI' ? 'bg-orange-100 text-orange-700' : 
                                            pred.prediction === 'EMCI' ? 'bg-amber-100 text-amber-700' : 
                                            pred.prediction === 'MCI' ? 'bg-yellow-100 text-yellow-700' : 
                                            'bg-emerald-100 text-emerald-700'
                                        }`}>
                                            {pred.prediction}
                                        </span>
                                    </h3>
                                    <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-1 text-sm text-gray-500">
                                        <span className="flex items-center gap-1"><Calendar size={14} /> {new Date(pred.createdAt).toLocaleDateString()}</span>
                                        <span className="flex items-center gap-1 font-semibold text-gray-900">
                                            <Activity size={14} className="text-indigo-600" /> 
                                            {Math.round(pred.confidence * 100)}% Confidence
                                        </span>
                                    </div>
                                </div>
                            </div>
                                <button 
                                    onClick={() => setSelectedReport({ type: 'prediction', data: pred })}
                                    className="px-6 py-3 bg-indigo-600 text-white hover:bg-indigo-700 rounded-xl transition-all shadow-md shadow-indigo-100 font-bold text-sm flex items-center gap-2"
                                >
                                    <FileText size={18} /> Full Case
                                </button>
                        </motion.div>
                    ))}

                    {activeTab === 'mri' && reports?.mriUploads?.map((mri, i) => (
                        <motion.div 
                            key={mri._id} 
                            initial={{ opacity: 0, y: 10 }} 
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.05 }}
                            className="p-6 hover:bg-gray-50/50 flex flex-col md:flex-row md:items-center justify-between gap-6"
                        >
                            <div className="flex items-center gap-4">
                                <div className="w-14 h-14 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center border border-blue-100 shadow-sm overflow-hidden">
                                    {mri.fileUrl || mri.filePath ? (
                                        <img src={getMediaUrl(mri.fileUrl || mri.filePath)} alt="MRI" className="w-full h-full object-cover" />
                                    ) : (
                                        <Brain size={28} />
                                    )}
                                </div>
                                <div>
                                    <h3 className="font-bold text-gray-900 text-lg flex items-center gap-2 truncate max-w-xs">
                                        {mri.fileName}
                                        {mri.result && (
                                            <span className={`text-[10px] px-2 py-0.5 rounded-full ${
                                                mri.result.prediction === 'AD' ? 'bg-rose-100 text-rose-700' : 
                                                mri.result.prediction === 'LMCI' ? 'bg-orange-100 text-orange-700' : 
                                                'bg-emerald-100 text-emerald-700'
                                            }`}>
                                                {mri.result.prediction}
                                            </span>
                                        )}
                                    </h3>
                                    <div className="flex items-center gap-4 mt-1 text-sm text-gray-500">
                                        <span className="flex items-center gap-1 font-medium text-gray-900"><User size={14} className="text-blue-500" /> {mri.user?.name || 'Unknown User'}</span>
                                        <span className="flex items-center gap-1"><Calendar size={14} /> {new Date(mri.uploadedAt).toLocaleDateString()}</span>
                                    </div>
                                </div>
                            </div>
                            <div className="flex items-center gap-3">
                                <button 
                                    onClick={() => setSelectedReport({ type: 'mri', data: mri })}
                                    className="p-3 bg-blue-600 text-white hover:bg-blue-700 rounded-xl transition-all shadow-md shadow-blue-100"
                                >
                                    <ChevronRight size={18} />
                                </button>
                            </div>
                        </motion.div>
                    ))}

                    {activeTab === 'cognitive' && reports?.cognitiveTests?.map((test, i) => (
                        <motion.div 
                            key={test._id} 
                            initial={{ opacity: 0, y: 10 }} 
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.05 }}
                            className="p-6 hover:bg-gray-50/50 flex flex-col md:flex-row md:items-center justify-between gap-6"
                        >
                            <div className="flex items-center gap-4">
                                <div className="w-14 h-14 bg-purple-50 text-purple-600 rounded-2xl flex items-center justify-center border border-purple-100 shadow-sm">
                                    <FileText size={28} />
                                </div>
                                <div>
                                    <h3 className="font-bold text-gray-900 text-lg flex items-center gap-2">
                                        Test: Cognitive Assessment
                                        <span className="text-xs px-2 py-0.5 bg-purple-100 text-purple-700 rounded-full font-bold">
                                            {test.totalScore != null ? `Symptoms: ${test.totalScore}/30` : `Symptoms: ${30 - test.mmseScore}/30`}
                                        </span>
                                        {test.result && (
                                            <span className={`text-[10px] px-2 py-0.5 rounded-full ${
                                                test.result.prediction === 'AD' ? 'bg-rose-100 text-rose-700' : 
                                                test.result.prediction === 'LMCI' ? 'bg-orange-100 text-orange-700' : 
                                                'bg-emerald-100 text-emerald-700'
                                            }`}>
                                                {test.result.prediction}
                                            </span>
                                        )}
                                    </h3>
                                    <div className="flex items-center gap-4 mt-1 text-sm text-gray-500">
                                        <span className="flex items-center gap-1 font-medium text-gray-900"><User size={14} className="text-purple-500" /> {test.user?.name || 'Unknown' }</span>
                                        <span className="flex items-center gap-1"><Calendar size={14} /> {new Date(test.submittedAt).toLocaleDateString()}</span>
                                    </div>
                                </div>
                            </div>
                            <div className="flex items-center gap-3">
                                <div className="hidden lg:flex gap-4 mr-4">
                                    <div className="text-center">
                                        <p className="text-[10px] font-bold text-gray-400 uppercase">Memory</p>
                                        <p className="text-sm font-bold text-gray-900">{test.memoryScore}%</p>
                                    </div>
                                    <div className="text-center">
                                        <p className="text-[10px] font-bold text-gray-400 uppercase">Attention</p>
                                        <p className="text-sm font-bold text-gray-900">{test.attentionScore}%</p>
                                    </div>
                                </div>
                                <button 
                                    onClick={() => setSelectedReport({ type: 'cognitive', data: test })}
                                    className="p-3 bg-purple-600 text-white hover:bg-purple-700 rounded-xl transition-all shadow-md shadow-purple-100"
                                >
                                    <ChevronRight size={18} />
                                </button>
                            </div>
                        </motion.div>
                    ))}

                    {/* Empty states if count is 0 */}
                    {reports?.[activeTab === 'predictions' ? 'predictions' : activeTab === 'mri' ? 'mriUploads' : 'cognitiveTests']?.length === 0 && (
                        <div className="p-20 text-center text-gray-400">
                            <FileText size={48} className="mx-auto mb-4 opacity-20" />
                            <p>No {activeTab} reports found in the system yet.</p>
                        </div>
                    )}
                </div>
            </div>
            {/* Detail Modal */}
            <AnimatePresence>
                {selectedReport && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                        <motion.div 
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            onClick={() => setSelectedReport(null)}
                            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                        />
                        <motion.div 
                            initial={{ scale: 0.95, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            exit={{ scale: 0.95, opacity: 0 }}
                            className="bg-white rounded-[2rem] shadow-2xl overflow-hidden max-w-2xl w-full relative z-10 border border-gray-100"
                        >
                            {/* Modal Header */}
                            <div className="px-8 py-6 bg-slate-900 text-white flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                    <div className="p-2 bg-indigo-500/20 rounded-xl border border-indigo-500/30 text-indigo-400">
                                        <Info size={20} />
                                    </div>
                                    <div>
                                        <h3 className="text-xl font-bold">Report Details</h3>
                                        <p className="text-xs text-slate-400">Case ID: {selectedReport.data._id}</p>
                                    </div>
                                </div>
                                <button 
                                    onClick={() => setSelectedReport(null)}
                                    className="p-2 hover:bg-white/10 rounded-xl transition-colors"
                                >
                                    <X size={20} />
                                </button>
                            </div>

                            <div className="p-8 space-y-6 max-h-[70vh] overflow-y-auto custom-scrollbar">
                                {/* Basic Info Card */}
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100">
                                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Patient Name</p>
                                        <p className="font-bold text-gray-900">{selectedReport.data.user?.name || 'Unknown'}</p>
                                    </div>
                                    <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100">
                                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Date Logged</p>
                                        <p className="font-bold text-gray-900">{new Date(selectedReport.data.createdAt || selectedReport.data.uploadedAt || selectedReport.data.submittedAt).toLocaleString()}</p>
                                    </div>
                                </div>

                                {/* Content Based on Type */}
                                {selectedReport.type === 'prediction' && (
                                    <div className="space-y-6">
                                        <div className="p-6 bg-indigo-50 rounded-3xl border border-indigo-100 flex items-center justify-between">
                                            <div>
                                                <h4 className="text-sm font-bold text-indigo-900 mb-1">AI Diagnostic Result</h4>
                                                <p className="text-3xl font-black text-indigo-600">{selectedReport.data.prediction}</p>
                                            </div>
                                            <div className="text-right">
                                                <p className="text-sm font-bold text-indigo-900 mb-1">Confidence Score</p>
                                                <p className="text-3xl font-black text-indigo-600">{Math.round(selectedReport.data.confidence * 100)}%</p>
                                            </div>
                                        </div>

                                        {/* MRI View for Prediction */}
                                        {(selectedReport.data.mriScan?.fileUrl || selectedReport.data.mriScan?.filePath) && (
                                            <div className="aspect-video bg-gray-100 rounded-3xl overflow-hidden border border-gray-200">
                                                <img 
                                                    src={getMediaUrl(selectedReport.data.mriScan.fileUrl || selectedReport.data.mriScan.filePath)} 
                                                    alt="Associated MRI" 
                                                    className="w-full h-full object-contain"
                                                />
                                            </div>
                                        )}

                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                            <div className="bg-white p-4 rounded-2xl border border-gray-200">
                                                <h5 className="text-xs font-bold text-gray-500 uppercase mb-3 flex items-center gap-2">
                                                    <Clock size={14} className="text-indigo-400" /> Processing Info
                                                </h5>
                                                <div className="space-y-2">
                                                    <div className="flex justify-between text-sm">
                                                        <span className="text-gray-500">Model Version</span>
                                                        <span className="font-bold">{selectedReport.data.modelVersion || 'v1.0.4'}</span>
                                                    </div>
                                                    <div className="flex justify-between text-sm">
                                                        <span className="text-gray-500">Compute Time</span>
                                                        <span className="font-bold">{selectedReport.data.processingTimeMs ? `${Math.round(selectedReport.data.processingTimeMs)}ms` : 'N/A'}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="bg-white p-4 rounded-2xl border border-gray-200">
                                                <h5 className="text-xs font-bold text-gray-500 uppercase mb-3 flex items-center gap-2">
                                                    <Zap size={14} className="text-amber-400" /> Clinical Data
                                                </h5>
                                                <div className="space-y-2">
                                                    <div className="flex justify-between text-sm">
                                                        <span className="text-gray-500">Total Symptom Count</span>
                                                        <span className="font-bold text-rose-600">{selectedReport.data.cognitiveTest?.totalScore ?? (30 - selectedReport.data.cognitiveTest?.mmseScore) ?? 'N/A'}/30</span>
                                                    </div>
                                                    <div className="flex justify-between text-sm">
                                                        <span className="text-gray-500">MRI Hash</span>
                                                        <span className="font-mono text-[10px] text-gray-400">{selectedReport.data.mriScan?._id?.slice(-12) || 'Direct Link'}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                )}

                                {selectedReport.type === 'mri' && (
                                    <div className="space-y-4">
                                        <div className="aspect-video bg-gray-100 rounded-3xl overflow-hidden border border-gray-200 group relative">
                                            <img 
                                                src={getMediaUrl(selectedReport.data.fileUrl || selectedReport.data.filePath)} 
                                                alt="MRI Full" 
                                                className="w-full h-full object-contain"
                                            />
                                        </div>
                                        <div className="bg-blue-50 p-4 rounded-2xl border border-blue-100 flex items-center justify-between">
                                            <div className="flex items-center gap-3">
                                                <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
                                                    <FileText size={18} />
                                                </div>
                                                <div>
                                                    <p className="text-sm font-bold text-blue-900">{selectedReport.data.fileName}</p>
                                                    <p className="text-xs text-blue-600">{(selectedReport.data.fileSize / 1024).toFixed(1)} KB • {selectedReport.data.mimeType}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                )}

                                {selectedReport.type === 'cognitive' && (
                                    <div className="space-y-6">
                                        <div className="p-6 bg-purple-50 rounded-3xl border border-purple-100 grid grid-cols-3 gap-4 text-center">
                                            <div>
                                                <p className="text-[10px] font-bold text-purple-400 uppercase tracking-widest mb-1">Memory</p>
                                                <p className="text-2xl font-black text-purple-700">{selectedReport.data.memoryScore}%</p>
                                            </div>
                                            <div>
                                                <p className="text-[10px] font-bold text-purple-400 uppercase tracking-widest mb-1">Language</p>
                                                <p className="text-2xl font-black text-purple-700">{selectedReport.data.languageScore}%</p>
                                            </div>
                                            <div>
                                                <p className="text-[10px] font-bold text-purple-400 uppercase tracking-widest mb-1">Attention</p>
                                                <p className="text-2xl font-black text-purple-700">{selectedReport.data.attentionScore}%</p>
                                            </div>
                                        </div>
                                        <div className="bg-white p-6 rounded-2xl border border-gray-200">
                                            <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
                                                <Activity size={16} className="text-purple-400" /> Assessment Score Breakdown
                                            </h4>
                                            <div className="space-y-4">
                                                <div className="flex justify-between items-center text-sm">
                                                    <span className="text-gray-500 font-medium">Total Symptom Count</span>
                                                    <span className="font-black text-rose-600 text-lg">{selectedReport.data.totalScore != null ? selectedReport.data.totalScore : (30 - selectedReport.data.mmseScore)}/30</span>
                                                </div>
                                                <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                                                    <div 
                                                        className="h-full bg-rose-500 rounded-full" 
                                                        style={{ width: `${((selectedReport.data.totalScore != null ? selectedReport.data.totalScore : (30 - selectedReport.data.mmseScore)) / 30) * 100}%` }}
                                                    />
                                                </div>
                                                <div className="flex justify-between items-center text-sm pt-2">
                                                    <span className="text-gray-500 font-medium">Orientation Score</span>
                                                    <span className="font-bold text-gray-900">{selectedReport.data.mocaScore ?? 'N/A'}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Modal Footer */}
                            <div className="px-8 py-6 bg-gray-50 border-t border-gray-100 flex gap-4">
                                <button 
                                    onClick={() => setSelectedReport(null)}
                                    className="flex-1 py-3 px-6 bg-white border border-gray-200 text-gray-700 font-bold rounded-2xl hover:bg-gray-100 transition-colors"
                                >
                                    Close View
                                </button>
                                <button 
                                    onClick={() => handleExport(selectedReport)}
                                    className="flex-1 py-3 px-6 bg-indigo-600 text-white font-bold rounded-2xl hover:bg-indigo-700 transition-shadow shadow-lg shadow-indigo-100 flex items-center justify-center gap-2"
                                >
                                    <Download size={18} /> Export Data
                                </button>
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
}
